### ISSUE TITLE
std::runtime_error on threadElemsExtents.prod()

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#113]
I am currently evaluate the alpaka back-ends on the [matmul](https://github.com/BenjaminW3/matmul) library and introduced the element layer into the cuda-backend kernel. This works fine for CPU
accelerators. But I get an error, when I try to run with cuda back-end. The following is the trimmed source code. The error occurs when calling `threadElemsExtents.prod()`:

    class GemmAlpakaSharedKernel
    {
    public:
        ALPAKA_NO_HOST_ACC_WARNING
        template<
            typename TAcc,
            typename TElem>
        ALPAKA_FN_ACC auto operator()(
            TAcc const & acc,
            TSize const & m, TSize const & n, TSize const & k,
            TElem const & alpha,
            TElem const * const MATMUL_RESTRICT A, TSize const & lda,
            TElem const * const MATMUL_RESTRICT B, TSize const & ldb,
            TElem const & beta,
            TElem * const MATMUL_RESTRICT C, TSize const & ldc) const
        -> void
        {
         
         // Number of elements per thread
         auto const threadElemsExtents(alpaka::workdiv::getWorkDiv<alpaka::Thread, alpaka::Elems>(acc));
         TSize const & threadElemsExtentX(threadElemsExtents[1u]);
         TSize const & threadElemsExtentY(threadElemsExtents[0u]);

         assert(N_ELEMENTS == threadElemsExtents.prod()); // Error from this line

        }
        
    };

The error output is the following: 

    100/home/zenker64/libs/alpaka/include/alpaka/stream/StreamCudaRtAsync.hpp(299) 'cudaStreamSynchronize( stream.m_spStreamCudaRtAsyncImpl->m_CudaStream)' returned error: 'an illegal memory access was encountered'!

    terminate called after throwing an instance of 'std::runtime_error'
    
    what():  /home/zenker64/libs/alpaka/include/alpaka/stream/StreamCudaRtAsync.hpp(299) 'cudaStreamSynchronize( stream.m_spStreamCudaRtAsyncImpl->m_CudaStream)' returned error: 'an illegal memory access was encountered'!

@BenjaminW3 do have any clue where this error is coming from ?

**Comment by BenjaminW3** [comment]
As far as I can see the asynchronous stream is used and `MATMUL_DEBUG` is set to 0 so that there is no debug wait after the execution of the kernel. Is this correct?
However, [this line](https://github.com/BenjaminW3/matmul/blob/develop/include/matmul/par/Alpaka.hpp#L448) correctly waits for the stream to finish with `cudaStreamSynchronize` before returning. All errors that occured during the execution of the asynchronous kernel are returned at his point. The error `an illegal memory access was encountered` would then most probably tell, that there was an out of bounds access on some buffer within the kernel.
There is no error without the line you commented? Could you verify this by commenting out all other commands within the kernel? If this is the case, there is most probably an error within `threadElemsExtents.prod()`. Could you test this method without the `assert` around? (Try to assure that the operation is not optimized away)

**Comment by BenjaminW3** [comment]
Closed for now as the current information do not show that the problem lies within alpaka itself.

**Comment by erikzenker** [comment]
The error did not occur again later. I don't know what fixed the problem. If something like this happens again, then I will make some noise.
