### ISSUE TITLE
HIP (HCC) Backend

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#151]
We should copy & replace the CUDA backend in a [HIP](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP) backend and see what happens.

Needs the [hcc](http://gpuopen.com/compute-product/hcc-heterogeneous-compute-compiler/) compiler (llvm based), install [see here](https://bitbucket.org/multicoreware/hcc/wiki/Home).

If this is successful one could also dig deeper and see what the [`<hc.hpp>` API](http://gpuopen.com/a-brief-intro-to-boltzmann-hcc/) itself offers and if it is possible to be integrated as an individual HC backend, too.

<3 Open Standards

**Comment by bussmann** [comment]
I heard you like CUDA so we put a Cupla in your code that uses Alpaka with a HIP backend to run it on a CUDA-enabled device.

**Comment by erikzenker** [comment]
AMD announced new accelerators with one TB of global memory. This is possible because they connect two ssd's directly with the accelerator (see [here](http://www.golem.de/news/radeon-pro-ssg-amd-zeigt-profi-karte-mit-ssds-fuer-ein-tbyte-videospeicher-1607-122332.html)). Dev kits are available in the end of 2016 for 10K euros. One reason more to provice a hip/hcc back-end.
