### ISSUE TITLE
trait to get stream type

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#175]
Currently the user needs background knowledge to get the right stream type depending on the selected device.
We need something that gets the stream out of the device or maybe out of the platform if #167 is merged.

Current usage:

``` C++
using AccDev = ::alpaka::dev::DevCpu;
//async stream
using AccStream = ::alpaka::stream::StreamCpuAsync;
//sync stream
using AccStream = ::alpaka::stream::StreamCpuAsync;

//or for GPU
using AccDev = ::alpaka::dev::DevCudaRt;
using AccStream = ::alpaka::stream::StreamCudaRtAsync;
using AccStream = ::alpaka::stream::StreamCudaRtSync;
```

My preferred way:

``` C++
using AccDev = ::alpaka::dev::DevCpu;
//async stream
using AccStream = ::alpaka::stream::getType<AccDev, ::alpaka::stream::Async>;
//sync stream
//using AccStream = ::alpaka::stream::getType<AccDev, ::alpaka::stream::Sync>;

//or for GPU
using AccDev = ::alpaka::dev::DevCudaRt;
using AccStream = ::alpaka::stream::getType<AccDev, ::alpaka::stream::Async>
using AccStream = ::alpaka::stream::getType<AccDev, ::alpaka::stream::Sync>
```

This needs no knowledge about the naming and which devices needs which stream type.

**Comment by erikzenker** [comment]
There exists already a similar methods for the unit tests:

`using Stream = alpaka::test::stream::DefaultStream<DevAcc>`

We should add `alpaka::stream::Async` or `alpaka::stream::Sync` like it was mentioned by @psychocoderHPC and move this method into the main library.

**Comment by BenjaminW3** [comment]
Initially this had been part of alpaka. I moved this into the test code because there is no clear association from a `Device` type to a `Stream` type. However, in the other direction there is a direct mapping of a `Stream` to a `Device`.
Users are free to implement other synchronous, asynchronous or even completely other types of `Stream`s for a specific `Device`. Therefore I think that there is no such general mapping and it is the task of the user to define which stream should be used for which device.
The types in alpaka are currently built as a tree with the edges pointing from the children to the parent types but not the other way around. This allows the user to extend the tree at any layer without having to change any existing code. 
The current hierarchy of concepts should look like this: (directed edgese mean 'the specific x type (origin) knows his specific y type (target)'; excuse my bad ascii art)

```
Platform <--> Device <--|<-- Event <----|
                        |               |
                        |<---------- Stream
                        |
                        |<--------------|
                        |               |
                        |<-- Exec <--> Acc
                        |
                        |<--> Buffer
```
This tree is currently not perfect as there are some bidirectional edges. The transitive edges are no problem at all and could easily be removed. The bidirectional edges `Platform` <-> `Device` and `Exec` <-> `Acc` are no problem at the moment as there is a one to one mapping between them currently.
The `BufType` trait that provides a `Buffer` type given a `Device` might not be the correct solution as the user might want to use his own specialized buffer when calling alloc.
A default `Stream` given a `Device` would equally introduce such a bidirectional edge. therefore I am sceptical about introducing this into the main library.

**Comment by psychocoderHPC** [comment]
But keep in mind we need some instance or trait which maps streams to devices, else it is not possible to write platform independent code without `#ifdef` in the user code.
We need for streams a trait or a factory like `alapka::mem:alloc:alloc()` else it is like we use `alpaka::mem::buf::cuda::BufCudaRt` directly.
A factory or trait not breaks the orthogonal concepts.

> Users are free to implement other synchronous, asynchronous or even completely other types of 
> Streams for a specific Device. Therefore I think that there is no such general mapping and it is the task 
> of the user to define which stream should be used for which device.

This mapping needs knowledge about restrictions of each device and stream and must be part of alpaka.

**Comment by erikzenker** [comment]
I think we need such default streams if we want to write algorithms which do not know its accelerator in advance (like it is done for the test cases). But we need to discuss if this "type factory" should be user or library code. I raise my hand for library code because this would simply the usage of alpaka for beginners. Experts are allowed to write their own factory if they need to.

**Comment by psychocoderHPC** [comment]
@ComputationalRadiationPhysics/alpaka-developers
This issue become more and more important for the usability of alpaka. I saw user code like that

```C++
#if NBODY_CUDA == 1
    using Queue = alpaka::queue::QueueCudaRtSync;
#else
    using Queue = alpaka::queue::QueueCpuSync;
#endif // NBODY_CUDA
```
This can be avoided by a trait.  We should have an eye on concepts to avoid that the user must have any `#ifdef` in his code to use alpaka.
