### ISSUE TITLE
AtomicStlLock only atomic inside a block?

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#222]
Is the implementation of `AtomicStlLock` only atomic for threads inside a block?
https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/atomic/AtomicStlLock.hpp#L73
The used mutex is part of the accelerator. Each block gets its own accelerator. This looks like that a atomic operation is **not** atomic between different blocks within a grid.

**Comment by BenjaminW3** [comment]
You are right, this is only atomic for blocks.

To make it atomic for the whole grid, we could do either of the following:
1. make the mutex static and therefore execute all atomic operations in all kernel grids in sequential order
2. make the mutex within AtomicStlLock a reference to a mutex hold by the Executor given to the Accelerator constructor

I would prefer version 2.

Sidenote:
CUDA itself implements something that is stricter then version 2, because it is even atomic for operations from different kernels accessing the same memory address. This would not be supported.
However, CUDA is less strict than both versions because the mutex version does not look at the memory adress but serializes all atomic operations independently of the memory adress.

Do you want to fix this?

**Comment by psychocoderHPC** [comment]
I will change this issue to bug because
- `atomics` e.g. withing `AccCpuThreads` are not atomic within a grid what is not written down anywhere.
- #221 is also effected

I will create first a small bugfix with the first version you descried. This is a minimal fix which slow down `AtomicStlLock` but make them atomic inside a grid.
After that I will work on #201 which solves this issue (maybe I need to implement your version 2)
