### ISSUE TITLE
CI tests not finish

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#236]
Currently all Ci tests not finish and we merge unstable changes.
We need to fix the CI test.

**Comment by BenjaminW3** [comment]
I do not see 'all' tests failing. Sometimes the AppVeyor Windows builds are failing due to network and other errors unrelated to alpaka itself. Restarting the job almost always fixes this.

**Comment by psychocoderHPC** [comment]
But #234 and #229 are failed builds

**Comment by psychocoderHPC** [comment]
I enabled the github feature for the branch `development` that 
  - disallow force push
  - and allow only merging if all tests are finished and success

I enabled the github feature for the branch `master` that 
  - disallow force push

@ComputationalRadiationPhysics/alpaka-maintainers

**Comment by BenjaminW3** [comment]
#234 was merged before all jobs had finished (it only contained comment removals).
#239 was merged even though some tests failed due to the maximum log length was exceeded because Travis CI had some network issues at that time.

Thanks for enabling those features. I will close this issue as the tests are all correct.

**Comment by psychocoderHPC** [comment]
Thx, should we disable the logs to avoid errors like in #229
