### ISSUE TITLE
Why does Alpaka support multidimensional memory?

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#268]
One big point about Alpaka is, that it is memory agnostic. So you can create and copy memory, but in the end only access it with a pointer.

But if I only get a pointer anyway and thus need to calculate the 1D memory position out of 2D coordinates, why does Alpaka support multidimensional memory in the first place?

**Comment by BenjaminW3** [comment]
The only reason to support such multidimensional memory is the support for multidimensional memory operations within CUDA.
Using a 2D copy for a submatrix (of a potentially huge matrix) instead of a 1D copy could be much more efficient because the (possibly huge) padding does not need to be copied by a 2D memory copy whereas it has to be copied when using a 1D copy. The same is true for memset as well.
To emulate the (possible) efficiency of such an ND-optimized memory copy you would have to make individual 1D copies for each line which is by far not equally efficient.
The larger an array gets, the more dimensions it has and the smaller the submatrix is (relatively), the higher is the potential benefit of such optimized operations.
However, I have to say that I do not know if this potential optimization is utilized by the CUDA runtime. Older CUDA versions did not do so.

**Comment by BenjaminW3** [comment]
Independent of the reasons for having those tight now, you are free to pass user defined memory views into your kernels instead of the raw pointers.
The build in views may not be suitable for this right now (this has not been tested/implemented right now) but this may be changed in the future.

**Comment by theZiz** [comment]
Thanks for the clarification, the cuda optimizations make sense.

**Comment by bussmann** [comment]
There are two other reasons imho. First, user convenience. Users sometimes like to write and read code that assumes a certain dimensionality of the data. Second, if you have a certain concept of iterating over the data, your code should reflect this on a high abstraction level. Nevertheless it is indeed questionable if Alpaka is conceptionally for these operations. Due to the reasons mentioned above it looks like it for now, but we should discuss this further.

**Comment by theZiz** [comment]
Yeah, I never doubt, that it is useful at all, but wonder whether this is the right place. This is the reason, why I started with a short paragraph about Alpaka being memory agnostig. ;)

**Comment by bussmann** [comment]
I believe some Alpaka concepts are common to both algorithmic parallelization and data parallelism and should thus be shared via a common third library/header file. It would be great to identify and isolate these.
