### ISSUE TITLE
alpaka::Elems support for alpaka::idx::getIdx?

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/alpaka#295]
I played a bit with `alpaka::idx::getIdx` to learn the differences between
* `alpaka::idx::getIdx<alpaka::Grid, alpaka::Threads>(acc)`,
* `alpaka::idx::getIdx<alpaka::Grid, alpaka::Block>(acc)` and
* `alpaka::idx::getIdx<alpaka::Block, alpaka::Threads>(acc)`
and noticed, that there is no `alpaka::Elems` implementation to get the ID of an elem on the grid, block or thread scale. For `alpaka::workdiv::getWorkDiv`, `alpaka::Elems` is working.
With this I could e.g. do thinks like
```C++
auto const globalElemIdx = alpaka::idx::getIdx<alpaka::Grid, alpaka::Elems>(acc);
auto const localElemExtent = alpaka::workdiv::getWorkDiv<alpaka::Thread, alpaka::Elems>(acc);
for (int id = globalElemIdx[0]; id < globalElemIdx[0] + localElemExtent[0]; i++)
  printf("%i\n",id);
```
I know, that it would also be possible to multiply with the extent of the elems myself, but imho it would be inconsistent to be forced to do it myself.

Is there a particular reason why this implementation is missing or did I overlook something?

**Comment by BenjaminW3** [comment]
Yes, there is a particular reason why those are missing. 
The `getIdx` method answers the question: Relative to the [`Grid`|`Block`] the current thread is part of, when further subdividing this into [`Blocks`|`Threads`], which one does the current thread belong to . When we would insert `Elem` for the second template parameter, this can not be answered with a single index but would possibly be a range of elements because each thread can possibly calculate multiple elements.
 
There is `alpaka::idx::getIdxThreadFirstElem(acc)` that returns the index of the first element belonging to the current thread. This should be exactly what you are looking for.

This may be a bit inconsistent but at the time I implemented this, I thought that it would be better to have this explicit differentiation. For `Blocks` and `Threads` you get the exact index via `getIdx`. For `Elems` you have to call the special `getIdxThreadFirstElem` method because you get the index of the first element of this thread.
