### ISSUE TITLE
CUDA 9.0

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#376]
CUDA 9.0 RC is available and I tried to test it within the CI. However, NVIDIA does not provide an installer for Ubuntu 14.04 anymore, which is the only available platform on Travis CI at the moment. CUDA 9.0 is only available for Ubuntu 16.04.
Furthermore, even if Travis CI would provide an Ubuntu 16.04 image within the next months, we would loose the ability to test the older CUDA releases 7.0 and 7.5 because they do not have support for Ubuntu 16.04.

Any ideas how to solve this (besides using docker)?

**Comment by ax3l** [comment]
For the CI, I would wait until the official release is out and than take [their official docker image](https://gitlab.com/nvidia/cuda). We just reported a few issues last week, currently boost is broken in all releases due to the dropping of `__CUDA_VER__` in CUDA 9 RC2 (https://github.com/boostorg/config/pull/152).

One could probably drop CUDA 7.0 in my eyes after the next alpaka tag / release.

What we are left with should be test-able with docker images for Ubuntu 16.04:
- official 16.04 non-free `nvidia-cuda-toolkit`: [CUDA 7.5](https://packages.ubuntu.com/xenial/nvidia-cuda-toolkit)
- official [Nvidia CUDA 8 image](https://gitlab.com/nvidia/cuda): based on Ubuntu 16.04
- upcoming CUDA 9 Nvidia Image: likely also Ubuntu 16.04 based?

**Comment by ax3l** [comment]
Uh wait. You could just install *all dependencies* with [spack](https://spack.io/), too!

**Comment by BenjaminW3** [comment]
Spack uses the `.runfile` of the corresponding CUDA version for installing. As there is no OS in the download path, this way of installing seems to be OS agnostic and could also work for Ubuntu 14.04. We could possibly use it for all CUDA versions.

**Comment by ax3l** [comment]
Yep, spack is really awesome.
Let us just put its dir into the travis-ci cache so it does not need to recompile every turn.

**Comment by ax3l** [comment]
Started working on it yesterday. We might need a bit more time and could deploy [spack binary repos](https://github.com/LLNL/spack/pull/4854) for that.

See: https://github.com/LLNL/spack/pull/5133

ccing @fabian-jung

**Comment by ax3l** [comment]
P.S.: we can also use spack docker files for travis now: https://github.com/LLNL/spack/pull/5582

We just need to prepare the images and push them to docker hub.
