### ISSUE TITLE
possible syncron stream bug

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#453]
@BenjaminW3  I need some help to under stand https://github.com/ComputationalRadiationPhysics/alpaka/blob/2e882f40635bf1854a1be9d592d3b77102df8e1e/include/alpaka/stream/StreamCudaRtSync.hpp#L240-L260

Could it be that we have a bug here? 
A synchronous operation means that the **task is executed** and **after** the task a wait operation is spawned. The linked code is doing a synchronization first and than executed the task, in the case the task is accessing a pointer and the some pointer is access directly after the task from the threads which is calling the task than we have a race condition.

Do I miss something?

**Comment by BenjaminW3** [comment]
I am not sure if I understand your question correctly. However, I will try to describe the intricacies of this code.

This code can be very confusing. The CPU back-end internally uses the `Enqueue` trait for everything (Kernels, MemCpy, Set, Callbacks, ...) because everything on the CPU can be described as a simple function call. So `alpaka::mem::copy`, `alpaka::mem::set`, etc. all internally simply call `alpaka::stream::enqueue`.

On the other side the GPU back-end does not map everything onto such a generic `enqueue` implementation. A call to `alpaka::mem::copy` for example, will directly call the cuda memcpy function. The function you have cited is the implementation for callbacks. The input is your synchronous stream and the callback function which is executed directly within the calling thread. I do not remember why we have to wait for a real callback from the underlying CUDA stream because there should never be anything outstanding in the synchronous stream (but only as long as no one else uses this same CUDA stream). For kernels there is a specializations of this `Enqueue` trait directly within the [ExecGpuCudaRt](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/exec/ExecGpuCudaRt.hpp#L276-L278).

**Comment by psychocoderHPC** [comment]
But if I am correct than this function is not blocking after the task work is finished. Could you please point to the code where we wait to finish the task before we give back the control to the calling thread.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by BenjaminW3** [comment]
As I have written above, the task in this case is a host callback function which is synchronously executed in the calling host thread. There is nothing to wait on. Stream callbacks for a synchronous stream are more or less useless. You could as well call the callback directly yourself (if you are sure that no one else enqueued something directly into the underlying CUDA stream).

**Comment by psychocoderHPC** [comment]
Thanks for the explenation.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
