### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jiradaherbst** [ComputationalRadiationPhysics/alpaka#483]
2. In the kernel section when I tried to traverse an array from back to front
               for (TIdx i(numElements-1); i>=0; --i)
                              C[i]=555;

the execution gave a segmentation fault. But when I changed to i>0, it was fine. Does TIdx restrict the numbers to >=0?

**Comment by BenjaminW3** [comment]
This is a simple programming error. Please make yourself comfortable with the way a [for loop](http://en.cppreference.com/w/cpp/language/for) works.
As long as the condition (i>=0) is true, the iteration expression `--i` and the body `C[i]=555` will be executed. So when `i==0`, ther will be another iteration and the next value will be `--0` which is most likely out of the array.

**Comment by theZiz** [comment]
No, this is not the case. The loop would be executed one last time (as intended) for `i==0` and for `i==-1` the condition would be false and the loop would **not** execute the loop body again.
However, I guess `TIdx` is an unsigned type, so `--i`is not `-1`, but the biggest possible positive number for this type, which is **always** bigger or same as zero. So basically you wrote an infinite loop, which crashes while accessing `C[0xFFF...FFF]` :wink:

**Comment by BenjaminW3** [comment]
You are right, I misinterpreted the loop. The effect is the same: out-of-bounds access ;-)

**Comment by theZiz** [comment]
To complete this problem, the loop could look like this
```C++
for (TIdx i(numElements-1); i<numElements; --i)
    C[i]=555;
```
With this we "exploit" the underflow as the condition becomes `false` after the underflow happened. However this of course works **only** if `TIdx` is unsigned! Otherwise you will get the error Benjamin described. So having both checks can make sense:
```C++
for (TIdx i(numElements-1); i>=0 && i<numElements; --i)
    C[i]=555;
```
hoping that the compiler sees that one of the both conditions will never be `false`. A last solution could be
```C++
for (TIdx i(numElements-1); i+1>0; --i)
    C[i]=555;
```
but I don't know whether the compiler is smart enough to **not** add one in every loop iteration...
For me the last one is the most beatiful, but decide yourself. If on doubt choose the fastest one. :wink:

**Comment by BenjaminW3** [comment]
To add another version:
```
for (TIdx i(numElements); i>0; --i)
    C[i-1]=555+1;
```

**Comment by jiradaherbst** [comment]
I realized that TIdx cannot be negative. So I solved it like this.

for (TIdx i(numElements); i>0; --i)
            {
                    TIdx ii(i-1);
                    C[ii]=555;
            }

*^^*

**Comment by ax3l** [comment]
that's ok as long as `ii` is const ;)
```C++
TIdx const ii(i-1);
C[ii]=555;
```

**Comment by jiradaherbst** [comment]
Thanks for all the answers!
