### ISSUE TITLE
activate required review

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#498]
@ComputationalRadiationPhysics/alpaka-maintainers I activated for the dev and master branch that at least one review of a maintainer is required before a PR can be merged.

**Comment by BenjaminW3** [comment]
I had the impression that at least the required review per PR had already been enabled some time before. Either my memory is wrong or it has been disabled somehow.
However, it does not matter now and you have reenabled everything. So I think everybody has recognized this change and the ticket can be closed.

**Comment by BenjaminW3** [comment]
I will for now disable the additional `Require review from Code Owners` rule because with this option, only those with write access to the repo can really approve a PR. Currently only admins have write access (because nobody else needs it). So the people which can approve a PR seem to be too limited (especially when someone is in holidays).
We can still reenable this option, but then we would need to extend the number of people with write access which I do not see necessary.

**Comment by ax3l** [comment]
That's exactly the idea. Everyone can review but at least a maintainer needs to approve as well.

**Comment by BenjaminW3** [comment]
I have now reenabled the `Require review from Code Owners` option but gave the @ComputationalRadiationPhysics/alpaka-developers write access to the repo. So they can now all approve and Merge Pull Requests.

**Comment by theZiz** [comment]
With great power comes great responsibility...
