### ISSUE TITLE
vectorization & warps

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/alpaka#51]
I opened this issue just to keep track of a discussion we had two weeks ago.

imho, one of the main screws we should deploy to allow fine-tuning and full utilization of hardware is to provide the possibility to actually steer vectorization (and to be warp-aware in CUDA-speak, which is actually the same as vectorization on CPUs).

Implementations on CPUs could achieve that by adding inner, constant-size loops and pragmas. (Example: loop 1 to n with n non-constant will not likely be vectorized, a loop 1 to n%8 with inner constant loops 0 to 7 might be more likely be vectorized.) Also, users could use that feature to avoid bank conflicts in "one thread per block" access schemes and it might be very useful on GPUs for synchronization and ptx/asm-specific calls.

I think we also defined the way to include this in the alpaka policy scheme, did you document that @BenjaminW3 ?

**Comment by BenjaminW3** [comment]
I am currently working on this topic.
In ```develop``` commit bb75954890be0717e8991c68ffae6a8becc3df66 I have added the ```GetCurrentThreadVectorRegisterSizeElems``` trait that returns the optimal compile time number of elements to loop over for a given data type in the current function.
A ```vectorize``` function has been implemented.
It can be called like this: ```vectorize<float>(n, [&](int const & i){Y[i]= alpha*X[i] + Y[i]})```
It mimics a for loop but internally loops in steps of the optimal vector size over the given number of elements which allows the optimizer to easily recognize the vectorizability of the loop even if the input loop count ```n``` was not a compile-time constant.

In branch ```topic-vectorization``` I have very promising results by extending the CUDA work division. Instead of a **grid** of **blocks** of **threads** I use a **grid** of **blocks** of **threads** of **elements**.
This allows to map a AXPY on CUDA into **blocks** of **threads** with each calculating one **element** while a sequential CPU version uses exactly one **block** and one **thread** iterating over all the **elements** within a loop in the **thread**. 
A parallel CPU implementation would be using multiple **blocks**, each with exactly one **thread** looping over a part of the vector **elements**.

Even if this is not exactly the model we discussed, it better maps the coarse grained CPU parallelism.

**Comment by ax3l** [comment]
thank you for the updated "grid of blocks of threads of elements" sounds great!

> while a sequential CPU version uses exactly one block and one thread iterating over all the elements within a loop in the thread. 

... or sequentially executing but vectorizing this one thread over n elements ;)

Looks like we can actually play around with various combinations now, would be really interesting to see if a simple profiler already provides us with a higher vector_pipeline utilization when using `elements`.

**Comment by BenjaminW3** [comment]
As this has been pushed to master, I will close the issue.
