### ISSUE TITLE
Zenodo webhook seems to be broken

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#521]
The zenodo webhook seems to be broken. We have not used it for the last releases so we could probably remove it.
However, it would be cool if this could get fixed.

**Comment by ax3l** [comment]
It still works and the `0.3.1` was successfully delivered.

Don't be confused with the last status, when we update the release text after the first release, e.g. to add the `DOI` badge, this triggers another webhook delivery. Zenodo will then check if it knows the release already (yes) and returns a `409` for "release already known". That's why it's red.

I still don't find why the `0.2.0` and the `0.3.0` releases did not hit Zenodo - did you manually disable it for those?

**Comment by BenjaminW3** [comment]
No, I simply created a normal release. I did nothing regarding zenodo (therefore no badges).

**Comment by ax3l** [comment]
Let us add a `.zenodo.json` so the meta data is filled in automatically on releases.

(Badges we have to add to the text manually anyway if we want to show them.)

**Comment by ax3l** [comment]
@BenjaminW3 do you have an [ORCiD](https://orcid.org/)?

**Comment by BenjaminW3** [comment]
no

**Comment by BenjaminW3** [comment]
I will close this ticket because you have answered why it seems to be broken but is not.
