### ISSUE TITLE
Remove the support to build each test on its own

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#543]
Currently each test can be build completely separate from all other tests. Each test is a new project which searches for `alpaka`, `boost` and the test `common` library and links them. They can be copied out of the alpaka repo and be built from anywhere as long as the `ALPAKA_ROOT` variable is correctly set.
This makes the CMakeLists unnecessarily complex.
The tests CMakeLists could be nearly half the size if we would only search for dependencies and apply test settings in the top-level `test` folders CMakeLists.txt. This is also the de-facto standard for CMake projects. I do not see a reason to extract single tests from the repo. The tests will always be built in combination with the alpaka library itself.
The examples currently have the same features. However, there I can see a reason why one would want to build them independently. Therefore I would keep everything as is for the examples.
What do you think?

**Comment by ax3l** [comment]
yes, tests don't need a full project, `.cmake` snippets are enought

Ideally tests should just be build with the root `CMakeLists.txt` as long as the CMake commonly standardized variable `BUILD_TESTING` is `ON`. This is what #476 added as interface (also #478 keeps this).

Instead of adding a `add_subdirectory` for each test, just `include()` them as `.cmake` files that define `targets` that use dependencies from the root `CMakeLists.txt` (*or* a `find_package(... CONFIG)` of alpaka). #478 tries to unify this further.
