### ISSUE TITLE
Thrust support or custom library ?

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#56]
On the way porting [HASEonGPU](https://github.com/ComputationalRadiationPhysics/haseongpu) to alpaka I need to use thrust vectors and some methods like reduce and exclusive scan. I had a discussion about a coexistence of alpaka and thrust last week with @psychocoderHPC and gave it a try. 

But, the more I think about it, it turns out for me that thrust is not the right way. There is no possibility to address more than one accelerator, because you need to specify the backend CUDA, OpenMP or TBB during compilation as compile option. A better approach would be the explicit set of the accelerator and device in the code e.g.: `vector<Acc, Type, Size>(dev, size, init)`

Its not a big problem to remove the thrust vectors and replace them again by plain memory buffers, initialize them and copy them to the device. But by providing vectors similar to the stl ones, thrust simplified and reduced the code base a lot. 

Therefore, a library that provides stl like container / data structures and algorithms with explicit accelerator and device setting would by very handy in my eyes.

**Comment by BenjaminW3** [comment]
I do not know exactly what Thrust vectors can and can not do.
alpaka already supports memory buffers allocated on a device in a similar fashion you intended.
```C++
alpaka::mem::buf::alloc<TElem, TDim, TSize>(dev, extents)
```

A one-dimensional buffer of 10000 floats on the accelerator device would then be created with:
```C++
auto buf1dDev(alpaka::mem::buf::alloc<float, alpaka::dim::DimInt<1u>, int>(devAcc, 10000));
```
 
You can allocate such a buffer for host and device and use ```alpaka::mem::view::copy(buf1dDev, buf1dHost, 10000)``` to copy the buffer filled on host side to the device.
Because alpaka buffers closely mimic CUDA buffers, allocation and initialization is seperated.
By calling ```alpaka::mem::view::getNativePtr``` the native pointer to the buffer can be obtained for direct access of the host memory on the host or to give the device pointer to the kernel.
See the sometime out-of-date documentation [here](http://computationalradiationphysics.github.io/alpaka/namespacealpaka_1_1mem_1_1buf.html) for operations supported on buffers or [here](http://computationalradiationphysics.github.io/alpaka/namespacealpaka_1_1mem_1_1view.html) for operations on views (buffers are views but views not necessarily buffers).

Functionality like reduce and exclusive scan are out of range for alpaka and would belong into an external library.

**Comment by ax3l** [comment]
@erikzenker imho, a library such as the STL or it's CUDA pendant, Thrust, are one abstraction level above alpaka. Since thrust is [already portable to multicore CPUs](https://thrust.github.io/) via OpenMP and TBB backends, we might just need to build a bridge and expose some calls for device selection, but I would recommend to resist putting actual STL features into alpaka. we will only end up building thrust and the full STL interfaces again, this will never be complete.

**Comment by erikzenker** [comment]
it was not my intention to integrate a stl like library into alpaka, but to think about a library on top of alpaka that makes device memory management easier (a little bit like it thrust does). The stl is huge and you are right: its almost impossible builidng up its interface again.

But, do you already have some memory allocation helper functions I could reuse then? Otherwise I will write my own.

**Comment by BenjaminW3** [comment]
Because such thrust like double-buffers would not be part of alpaka (as far as I can assess for now), I will close this issue.
