### ISSUE TITLE
alpaka::atomic::atomicOp wrong template argument description

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#59]
The template argument type of first argument of the [atomicOp](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/atomic/Traits.hpp#L66) constructor suggests to give an atomic type but it should be the accelerator type, right ?

For example : 
`alpaka::atomic::atomicOp<alpaka::atomic::op::Add>(>>>acc<<<, myPtr, 1);`

**Comment by BenjaminW3** [comment]
Yes, the accelerator is correct but not necessary.
The ```atomicOp``` expects an type as first argument that specializes the atomic operation trait ```AtomicOp```, therefore it is called atomic.
The accelerator specializes this trait (indirectly) in the same way it specializes the ```GetIdx``` trait necessary for the ```getIdx<...,...>(idx)``` function.

**Comment by erikzenker** [comment]
So your are planing to insert other types than Accelerators ?

**Comment by BenjaminW3** [comment]
No, but multiple accelerators share the same index, atomicOp, etc. implementation via inheritance from a class only implementing this single aspect of an accelerator. Therefore the traits only expect a type implementing this single concept.

**Comment by erikzenker** [comment]
I just stumpled upon this TAtomic type and could not clarify from docs or code which kind of type I should feed in. Therefore, I think it is more clear if we would call it TAcc and add a description in doxygen e.g.: `\tparam TAcc Accelerator type that need to specialize the atomicOp trait`

**Comment by BenjaminW3** [comment]
Because `TAtomic` can be anything that can provide atomic operations, the name is correct. Instances of types like `AtomicCudaBuiltIn`, `AtomicNoOp`, `AtomicOmpCritSec` and `AtomicStlLock` can be used as `atomicOp`'s first parameter. The Accelerators inherit from those types and provide those atomic operations via a base class template specialization referal.
This naming is consistent with all other such methods. `TAtomic` specifies the concept the parameter type has to fulfill to be used with the template. The usage and the errors on wrong usage will be much clearer as soon as concepts are supported by the C++ language.
Other usages of this naming are e.g.: `alpaka::block::sync::syncBlockThreads<TBlockSync>` and `alpaka::workdiv::getWorkDiv<TOrigin, TUnit, TWorkDiv>` even though both of them can in the end be called with an accelerator.
