### ISSUE TITLE
Add compiler messages when there is no specialization for atomics.

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/alpaka#614]
In AtomicCudaBuiltIn.hpp, there are some checks for PTX version:
```C
#if BOOST_ARCH_PTX >= BOOST_VERSION_NUMBER(3, 5, 0)
/// ... AtomicOp ...
#endif
```
There should be an else branch with a `#error` or `static_assert()`, otherwise user might have to search for a while until the reason for a missing type becomes clear. Maybe there are other places as well (this `BOOST_ARCH_PTX` thing only affects atomics code, will be the same for HIP).
I'll check into it later.

**Comment by BenjaminW3** [comment]
I think that `#error` would not work because this would break compilation for lower versions even though the specific type is not used.
We should add a specialization for the else path as well (or move the `#if` into the existing specialization) and add a compile time error when it is used.
However, there is a huge number of types that are not supported by the CUDA backend. This would only add better output for those specializations that are only available depending on the PTX version. For all the others we would still get the original error.

**Comment by tdd11235813** [comment]
> We should add a specialization for the else path as well (or move the #if into the existing specialization) and add a compile time error when it is used.

Sounds good in the first place, but you are right, that there would be inconsistency, as for one type you have a proper compile error message, while for the other one still a non-fancy error message appears.

So maybe provide a template base class, which emits such an error in the fallback case, while the specializations "overwrite" this behavior (just in the style of static polymorphism or SFINAEing).
But this is really not a must-have feature to me and not worth a refactoring, so you may decide how to proceed with this issue ;)
