### ISSUE TITLE
Drop support for Ubuntu 14.04

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/alpaka#626]
Ubuntu 14.04 is now more than 4 years old and most systems should be running 16.04 or even 18.04 now. CUDA already dropped support for 14.04 some time ago (even though one can still install CUDA 9.2 on Ubuntu 14.04). So is there any reason to still use this old version?

Support for 18.04 should be added as well. It might not be possible to install all CUDA version with this OS, but we should still test native compilation.

**Comment by tdd11235813** [comment]
I think the time is not too bad to drop support for Ubuntu14.04, which does not mean, it does not work (for now, but it is like deprecated now). 14.04 LTS ends in April 2019, while 18.04 LTS is already out there.

**Comment by theZiz** [comment]
Imho there is one good reason: It is still supported until April '19. :wink: Even if Nvidia drops the support, at least Cuda 8 can still be installed. So I don't see a good reason to drop the support for the next half year.
Is there any benefit for you like less maintaining effort?
We don't know exactly what our partners are using. I only know that e.g. the DLR has some Linux servers for their GPU tasks but no idea which version of what distribution they're using.

**Comment by ax3l** [comment]
The last two LTS releases (16.04 & 18.04) are very often used, getting especially 18.04 users in every day and we should cover this.

Regarding 14.04 the first thing we need to be aware if is that there are people out there using GCC 4.8 as their default compiler. There would be more reasons to support still GCC 4.8, e.g. for Python projects built on Alpaka, but since we are GCC 4.9+ that's already gone anyway (and GCC 4.8 is a pain anyway with regards to C++11, definitely not worth the effort.)

Besides that, `glibc` is still at `2.19` and has nifty bugs like #624, e.g. Hypnos (HZDR). But also Titan (ORNL) has this issue with SUSE Enterprise 11.

That said, I think it's less about "support for Ubuntu 14.04" but more about being aware which compilers, `glibc` and stdlibs we support. I would keep supporting old `glibc`s since it's not hard to fix the bugs we came across so far.

As long as we don't have proper installers which then enable packaging I don't dare yet to speak about supporting a certain OS, since we simply don't ;-)

**Comment by ax3l** [comment]
nevertheless, we should add testing for 18.04. I think AppVeyor Linux and CircleCI already have images.

**Comment by BenjaminW3** [comment]
We are not limited to what the CI systems provide. Alpaka builds completely within docker containers. We simply have to set the correct base container. I will give 18.04 a try and wait with removing 14.04 until next year.
