### ISSUE TITLE
Make ViewPlainPtr more convenient to use

### ISSUE THREAD

**Issue by krzikalla** [ComputationalRadiationPhysics/alpaka#642]
Following code:

```
alpaka::vec::Vec<alpaka::dim::DimInt<1>, size_t> size;
using TBuf = decltype(alpaka::mem::buf::alloc<T, size_t>(device, size));
auto buffer = alpaka::mem::buf::alloc<T, size_t>(device, size);
T* native_buf = static_cast<T*>(alpaka::mem::view::getPtrNative(buffer));
//...
ViewPlainPtr<???> view_buf(native_buf, device, size);
```

How can I figure out the template parameters of ViewPlainPtr (or the type altogether), given, that I can use TBuf at that code line? A function template would already help wrt. TDev and TElem. What would also be of a great help are some member typedefs in TBuf. Eventually I'd like to write

```
auto view_buf = GetViewPlainPtr(native_buf, device, size);
```

This one fails:
```
  template<typename TDev, typename TElem, typename TExtent>
  auto getViewPlainPtr(TElem* ptr, TDev const& dev, TExtent const & extent)
  {
    using namespace alpaka;
    return mem::view::ViewPlainPtr<TDev, TElem, dim::traits::DimType<TExtent>, size::traits::SizeType<TExtent>>(ptr, dev, extent);
  }
```
How do I figure out the dim type and the size type?

**Comment by BenjaminW3** [comment]
Alpaka mostly uses the way of specialization of exernal trait templates instead of member typedefs.

>How do I figure out the dim type and the size type?

To get the `Dim` of a type you can use `using BufDim = alpaka::dim::Dim<TBuf>;` and the size is equivalent. (Note that the `Size` type has been renamed to `Idx` on the develop branch).

> How can I figure out the template parameters of ViewPlainPtr (or the type altogether), given, that I can use TBuf at that code line?

Final type of a `ViewPlainPtr` given any other view (buffer itself, ViewSubView, ViewPlainPtr, ...) should be something like:
```
template<
    typename TView>
using ViewPlainPtrFromView = alpaka::mem::view::ViewPlainPtr<
    alpaka::dev::Dev<TView>,
    alpaka::elem::Elem<TView>,
    alpaka::dim::Dim<TView>,
    alpaka::idx::Idx<TIdx>>;
```

It is identical for a `ViewSubView`:
```
template<
    typename TView>
using ViewSubViewFromView = alpaka::mem::view::ViewSubView<
    alpaka::dev::Dev<TView>,
    alpaka::elem::Elem<TView>,
    alpaka::dim::Dim<TView>,
    alpaka::idx::Idx<TIdx>>;
```

So we should be able to have a generaic `ViewTransform`:
```
template<
    template<typename TDev, typename TElem, typename TDim, typename TIdx> class TDstView,
    typename TSrcView>
using ViewTransform = TDstView<
    alpaka::dev::Dev<TSrcView>,
    alpaka::elem::Elem<TSrcView>,
    alpaka::dim::Dim<TSrcView>,
    alpaka::idx::Idx<TSrcView>>;
```
that can be called like this:
```
using ViewPlainPtrFromView = ViewTransform<alpaka::mem::view::ViewPlainPtr, TBuf>;
using ViewSubViewFromView = ViewTransform<alpaka::mem::view::ViewSubView, TBuf>;
```

Please note: Nothing of this code has ever seen a compiler so it might not work at all ;-)

**Comment by BenjaminW3** [comment]
Above should be the answer, but why do you try to convert a buffer to a `ViewPlainPtr`? A buffer is a view so it is already usable in all places where views are expected.

**Comment by krzikalla** [comment]
But sometimes I don't have a buffer. A more comprehensive example:

```
alpaka::vec::Vec<alpaka::dim::DimInt<1>, size_t> size;
using TBuf = decltype(alpaka::mem::buf::alloc<T, size_t>(device, size));
std::optional<TBuf> buffer;
T* native_buf = getMemory();
if (native_buf == nullptr)
{
  buffer = alpaka::mem::buf::alloc<T, size_t>(device, size);
  native_buf = static_cast<T*>(alpaka::mem::view::getPtrNative(buffer));
}
ViewPlainPtr<...> view_buf(native_buf, device, size);
if (buffer)
  alpaka::mem::view::copy(stream, *buffer, otherBuffer, size);
else
  alpaka::mem::view::copy(stream, view_buf, otherBuffer, size);
```

I wonder if I might loose something if I omit the second branch and always go with view_buf there?

**Comment by BenjaminW3** [comment]
It should be perfectly fine to create the `view_buf` either from the native pointer or from the alpaka buffer. As written above, you should be able to use `ViewPlainPtr<alpaka::dev::Dev<TBuf>, alpaka::elem::Elem<TBuf>, alpaka::dim::Dim<TBuf>, alpaka::idx::Idx<TBuf>>` as your type (or size instead of idx depending on your alpaka version).

**Comment by BenjaminW3** [comment]
Is there anything to do here that is not mentioned in #643 or #655?

**Comment by BenjaminW3** [comment]
I will close this ticket because there does not seem to be anything left here which is not part of other tickets.
