### ISSUE TITLE
Intel compiler cpuid on linux

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/alpaka#66]
Compiling alpaka with the intel compiler on linux throws:

`/home/zenker64/haseongpu_alpaka3/include/alpaka/include/alpaka/dev/cpu/SysInfo.hpp(89): error: identifier "cpuid" is undefined
                      cpuid(0x80000000, 0, ex);`

Using [this](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/dev/cpu/SysInfo.hpp#L62-L66) execution branch for linux compiles.

**Comment by BenjaminW3** [comment]
I have tried to fix it in the `fix-intel-cpuid` branch. Can you check if this works?
In my last test the Intel compiler had some bugs that prevented a successful compilation of some template heavy parts of alpaka.

**Comment by erikzenker** [comment]
I will check, but also recognized the problems with the intel compiler. Do you have plans to support intel compiler for the future ?

**Comment by BenjaminW3** [comment]
I really want to support it, because it is a major compiler generating fast code but also because it supports Offloading to Xeon Phi in a OpenMP 2 extension.
I think it will be hard work because some of the template errors are really deep within variadic templates iterating over a std::integer_sequence. I would be happy if someone would have a look at it :smile:

**Comment by BenjaminW3** [comment]
All the ICC incompatibilites have been fixed/worked around in commits f9cd663b81d42f26b71b5391a4702b283bffa4d9, 864406429b23c12610576d12ea2f168392bde19d, 83ddac55624edf38085a160aeebd046b7fd2c5ad, b9f099c558edddbf619d0c2123bed995171d308f and 9dfdb96b0cb2fc32a1f2e447de755905f7538bf4.

**Comment by erikzenker** [comment]
You are great :honeybee:

**Comment by psychocoderHPC** [comment]
thanks! great work.
