### ISSUE TITLE
ALPAKA ignore cuda errors?

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#74]
@BenjaminW3 
I run picongpu with alpaka:
If I set `ALPAKA_DEBUG` to `2` I get an error `The execution of kernel 'N8picongpu26KernelMoveAndMarkParticlesIN5PMacc20SuperCellDescriptionINS1_4math2CT6VectorIN4mpl_10integral_cIiLi8EEES8_NS7_IiLi4EEEEENS4_3IntILi1ELi1ELi1EEENSB_ILi2ELi2ELi2EEEEEEE' failed with error: 'out of memory'`
If set it to `0`v (zero) the simulation runs without an error. It looks like the error is not translated to an exception.

Can you give me a short overview about the error handling in alpaka.

**Comment by BenjaminW3** [comment]
The alpaka library currently has 3 debug levels.

 * `ALPAKA_DEBUG == 0`
  There are only some basic C++ `assert` calls for values that do not have to be computed extra.

 * `ALPAKA_DEBUG == 1`
  Additional checks are enabled that can possibly have a measurable performance impact because extra values have to be computed. For example, the work division is tested for validity on each kernel call, which requires to get the device properties. Furthermore, the kernel calls are checked for errors only starting at this level because this requires synchronization after each kernel call.

 * `ALPAKA_DEBUG == 2`
  This level mostly outputs intermediate values, e.g. sizes, pitches and pointers of buffers on each copy or the values returned by `cudaFuncGetAttributes` on each kernel call and spams the output.

**Comment by psychocoderHPC** [comment]
Thanks for the description!

It looks like if `ALPAKA_DEBUG == 0` than I not receive errors from previous kernel launch errors.
Might be than previous errors are deleted by [this line](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/core/Cuda.hpp#L93), if so than it is a **BUG**

**Comment by BenjaminW3** [comment]
Currently this line erases the previous error by intent because it can be really confusing to get errors at a totally unrelated code line because the kernel errors are written back asynchronously.
However, I can understand that those errors should not be fully ignored.
I will have a look at it.
