### ISSUE TITLE
BOOST_COMP_GNUC is valid on device side

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#92]
@BenjaminW3 Do you know that `BOOST_COMP_GNUC` is valid on host and device if the host compiler is gnu?
My current host compiler ist gcc 4.9 and  `BOOST_COMP_GNUC == 40900002` on host and device.
Maybe this is new for @BenjaminW3 and has side effects where `BOOST_COMP_GNUC` is used.

IMO the reason is that the host precompiler of the host compiler is used.

**Comment by BenjaminW3** [comment]
As you said the compiler that boost.predef identifies is always the compiler wrapped by nvcc irrespective of host/device code. This can be gcc, clang, icc as well as MSVC depending on the system.
As far as I know, those macros are only used for workarounds for compiler bugs. This means that in the worst case a workaround is used within the device code instead of the original version even though the nvcc compiler would have correctly compiled the original code.

**Comment by BenjaminW3** [comment]
Closed because there is nothing to do.
